name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: remix-prisma-starter-test
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - uses: marocchino/tool-versions-action@v1
        id: versions

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.versions.outputs.nodejs }}

      - name: Get npm store directory
        id: npm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(npm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup npm cache
        with:
          path: ${{ steps.npm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-npm-store-${{ hashFiles('**/npm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-npm-store-

      - name: Cache playwright deps
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-build-playwright-${{ hashFiles('**/npm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-playwright-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          npm i
          npx playwright install

      - name: Lint
        run: |
          npm prisma generate
          npm lint
          npm ts-check

      - name: E2E
        run: |
          npm prisma db push
          npm build
          npm test:ci
        env:
          SECRET_KEY_BASE: supersecret42069
          DATABASE_PRISMA_URL: postgres://postgres:postgres@localhost:5432/remix-prisma-starter-test
          DATABASE_URL_NON_POOLING: postgres://postgres:postgres@localhost:5432/remix-prisma-starter-test
          SECURE_AUTH_COOKIE: false
          NODE_ENV: production
          PORT: 3001
